Moved and updated password gate
Alexintosh/PIE-landing pull request #85
Opened 2020-02-10 21:05 UTC by MickdeGraaf

##### Description

We want most parts of the website to be accessible without needing to enter a password. The passwordGate is updated so it asks for the password when it renders instead of when its imported.

##### Checklist

- [ ] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Testing

With a cleared cache visit the website and check if you can view it without a password. Then go to the mint/redeem page and check if it asks for it. Enter your password and the page should be available. Then go to the portfolio page and make sure it does not ask for the password again. Repeat above going first to the portfolio page and then to the mint/redeem page.

2020-02-11 19:24 UTC, dmvt requested changes
Currently this breaks the site if you click cancel and displays the password incorrect message immediately behind the password box. That's a bit clunky. Please change the following:

- [x] No password incorrect message until after an incorrect password is submitted
- [x] a link to reload and reenter the password with the bad password message
- [x] cancel button returns the user to the home page

2020-02-12 12:32 UTC, MickdeGraaf commented
Fixed the issues mentioned above. There is a refresh link now but it needs some styling to be visible @dimarconicola Can you look at it?

2020-02-13 12:10 UTC, dmvt approved these changes

2020-02-13 14:58 UTC, dimarconicola commented
I've tested it and it looks good to me:
- I've cleared the cache
- It doesn't ask for the password on the homepage
- It asks for the password for the portfolio page
- Both buy and redeem work fine

2020-02-13 14:58 UTC, dimarconicola approved these changes

2020-02-13 15:12 UTC, merged