WIP Add etherscan link to transaction overview
Alexintosh/PIE-landing pull request #95
Opened 2020-02-12 16:12 UTC by MickdeGraaf

##### Description

Adds a link to the transactions in the overview so users can inspect their transactions on Etherscan

##### Checklist

- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Testing

Go to the portfolio page and click the tx link.

##### Refers/Fixes

#54

2020-02-12 16:12 UTC, MickdeGraaf commented
@dimarconicola Can you style the link?

2020-02-13 15:15 UTC, dimarconicola commented
lgtm but I would add the following improvements for a next PR:
- [ ] etherscan link on the transaction list needs some styling
- [ ] date format is GMT by default but it would be nice to change it according to location

2020-02-13 15:15 UTC, dimarconicola approved these changes

2020-02-18 12:08 UTC, dimarconicola commented
tested and lgtm @dmvt @MickdeGraaf

2020-02-21 12:12 UTC, dmvt requested changes

2020-02-21 12:12 UTC, dmvt commented on src/components/TransactionsTable.jsx
> +  const { chainId } = useWeb3React();
Please standardize around the `eth` store instead. `eth.networkId`. We don't always fully initialize web3React.

2020-02-21 12:12 UTC, dmvt commented
Also as a reminder, if you think it's ready to go, remove the WIP

2020-02-21 12:58 UTC, dmvt approved these changes

2020-02-21 13:14 UTC, merged